releases:
- name: fzf
  repo: junegunn/fzf
  version: v0.57.0
  file_list:
  - linux,amd64:amd64
  - linux,arm64:arm
- name: dust
  repo: bootandy/dust
  version: v1.1.1
  file_list:
  - x86_64-unknown-linux-gnu:amd64
  - arm-unknown-linux-gnu:arm
- name: eza
  repo: eza-community/eza
  version: v0.20.13
  file_list:
  - eza_arm-unknown-linux-gnueabihf:arm
  - eza_x86_64-unknown-linux-gnu:amd64
